baseURL: https://ireland.onrender.com
languageCode: en-us
title: Come To Ireland!

params:
    customvariable: 15

menu:
    main:
    -   identifier: home
        name: Home
        url: /

    -   identifier: about
        name: About
        url: /about/

markup:
    goldmark:
        renderer:
            unsafe: true
